### ISSUE TITLE
Ignore requested_reviewers if PR is approved

### ISSUE THREAD

**Issue by christophehurpeau** [ewolfe/prlint#45]
Is there a way to ignore `requested_reviewers` when the PR is approved ?

Example of the issue:
- PR is opened with a reviewer: prlint ok
- someone review the pr and approve: prlint ok
- "update branch" button to merge master in the branch : prlint fail, event if the pr is still approved

**Comment by christophehurpeau** [comment]
Config is :  

```
{
  "requested_reviewers.0.id": [
    {
      "pattern": "\\d",
      "message": "Missing reviewer"
    }
  ]
}
```

**Comment by ewolfe** [comment]
Off the top of my head, not sure of a way to do this. I can look more into this when I get back from vacation though.

/remind me to look into this issue in 5 days

**Comment by ewolfe** [comment]
Sorry for the delay. Just opened an issue in a sandbox repo to replicate this. Would you mind going here https://github.com/ewolfe/sandbox/pull/16/files and approving it

**Comment by ewolfe** [comment]
Wanted to post an update on this. (As an aside, some other conversation took place over at https://github.com/ewolfe/sandbox/pull/17)

I sent GitHub a message:

> Issue: "requested_reviewers" doesn't work as expected.
> 
> To reproduce:
> 
> 1. Open a pull request and at the same time add a reviewer
> 2. Inspect the webhook payload and notice the reviewer is in the "requested_reviewers" array.
> 3. Have the reviewer approve the pull request
> 4. Inspect the new webhook payload and notice the reviewer has been removed from the "requested_reviewers" array.
> 
> Why would they get removed from the array just because they approved the pull request? It seems that would only make sense if the array was called "pending reviewers".

And they responded:

> Thanks for reaching out. What you observed is actually expected behavior for now. After a user reviews a pull request, the associated review request is removed (since the user performed the action that was requested). If you'd like to maintain the review request to indicate that the user should review it again -- you'd need to create another review request, either via the UI or the API. 
> 
> May I ask why you expected different behavior exactly? Is it just because of the name or is it because you'd find the behavior you described useful? If so, could you describe your use-case a bit more? Perhaps we can offer some advice (can't promise we will, but we're happy to listen and try).

I never followed up with them since I wasn't confident they would change the endpoint's behavior for my small project. So unfortunately, this means I don't have an answer for this use case. However, if the use case is to enforce X number of reviewers (which was my original intent when writing the docs and including the config you posted), then it looks like that's actually built into GitHub now. https://blog.github.com/2018-03-23-require-multiple-reviewers/ (something that came out after I launched this project 😉)

I'm going to go ahead and close this issue. Let me know if you need anything else. Cheers!

**Comment by christophehurpeau** [comment]
Thank you for your update ! The use case was to force to request someone for a review at the PR creation (or right after) with a message explaining why. The team now took the habit so we don't really need the rule, even if it would have been nice :)
Thank you !
