### ISSUE TITLE
Cannot Access `prlint.json` in forks

### ISSUE THREAD

**Issue by hjylewis** [ewolfe/prlint#59]
When a PR is made from the fork to the original repo, the error "`.github/prlint.json` not found" is displayed despite that file being present in the fork.

My guess is that PRLint does not have permission to access the file in the forked repo? Is there anything we can do to fix this? Many github work flows rely on creating PRs from forks.

**Comment by ewolfe** [comment]
Interesting, definitely a case I hadn't considered.

If the fork is public then it's probably trivial to fix this. If the fork is private, I'll have to verify if GitHub's API will allow PRLint to access it's contents. My guess is that the answer is no... Just because you forked a project, doesn't mean you consent to letting all of it's connected apps have access to your new files/source code.

I plan on giving this project some T.L.C. this month (rewriting tests, updating dependencies, etc). But I can't make any guarantees. If you want to help out and open a pull request to fix your issue I'll definitely merge it in!

**Comment by m3rabb** [comment]
Hi @ewolfe, sadly the forks we're using are private. We hope you'll have success. If not, we'll find a workaround. Thanks.

**Comment by ewolfe** [comment]
@m3rabb A quick fix might be to just "install" prlint to your fork. Would you mind trying that and letting me know? I can hop on a chat or video call too, it might be faster to debug that way.

**Comment by m3rabb** [comment]
@ewolfe, sure! Do you want to set a time for Mon 2018-09-10, or Sun 2018-09-09? I'm on Central time.

**Comment by ewolfe** [comment]
@m3rabb sorry, just saw your message. I can do anytime today, you can send me a Google Hangouts link on here or to my email (it's listed on my profile)

**Comment by ewolfe** [comment]
Just deployed a fix for this (via https://github.com/ewolfe/prlint/pull/62)!
